FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml README.md /app/
COPY src /app/src
COPY api /app/api
COPY migrations /app/migrations

RUN pip install --no-cache-dir -e /app

EXPOSE 8000
CMD ["uvicorn","api.app.main:app","--host","0.0.0.0","--port","8000"]
